# объект - игрушка
obj_name = "игрушка_1" #str
obj_type = "машинка" #str
obj_price = 133.2    #float
obj_id = 15          #int
print(f"{obj_name}; type = {type(obj_name)}")
print(f"{obj_type}; type = {type(obj_type)}")
print(f"{obj_price}; type = {type(obj_price)}")
print(f"{obj_id}; type = {type(obj_id)}")